### ISSUE TITLE
Add schema property

### ISSUE THREAD

**Issue by akefirad** [datreeio/datree-cdk8s#7]
Would be nice to be able to set the K8S version for schema validation. Happy to send a PR

**Comment by shmu3l** [comment]
Hey, thanks for the issue:) Not quite sure what you mean, we decided to skip the k8s schema validation part of the Datree test, since this happens during compilation for typed languages.
Can you clarify what you mean?

**Comment by akefirad** [comment]
Yes, that's what I mean. So no schema-validation, right? (if so, then feel free to close the issue.)
